version: '3.8'

services:
  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    networks:
      - app-network

  postservice:
    image: ${DOCKER_REGISTRY-}postservice
    build:
      context: ./PostService
      dockerfile: Dockerfile
    ports:
      - "5010:8080" 
      - "5011:8081"
    networks:
      - app-network

  feedService:
    image: ${DOCKER_REGISTRY-}feedservice
    build:
      context: ./FeedService
      dockerfile: Dockerfile
    ports:
      - "5020:8080"
      - "5021:8081"
    networks:
    - app-network

networks:
  app-network:
    driver: bridge
