version: '3.8'

services:
  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    networks:
      - app-network

  postservice:
    image: ${DOCKER_REGISTRY-}postservice
    build:
      context: .
      dockerfile: PostService/Dockerfile
    ports:
      - "5010:8080" 
      - "5011:8081"
    networks:
      - app-network

  feedService:
    image: ${DOCKER_REGISTRY-}feedservice
    build:
      context: .
      dockerfile: FeedService/Dockerfile
    ports:
      - "5020:8080"
      - "5021:8081"
    networks:
    - app-network

  ocelotGateway:
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: .
      dockerfile: OcelotGateway/Dockerfile
    ports:
      - "5554:8080"
      - "5555:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
