version: '3.8'

services:
  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "5000:8080"  # Map host port 5000 to container port 8080 (HTTP)
      - "5001:8081"  # Map host port 5001 to container port 8081 (HTTPS)
    networks:
      - app-network

  postservice:
    image: ${DOCKER_REGISTRY-}postservice
    build:
      context: ./PostService
      dockerfile: Dockerfile
    ports:
      - "5002:8080"  # Map host port 5002 to container port 8080 (HTTP)
      - "5003:8081"  # Map host port 5003 to container port 8081 (HTTPS) - "5001:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
