apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: feedservice
  name: feedservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: feedservice
  template:
    metadata:
      labels:
        io.kompose.service: feedservice
    spec:
      containers:
        - name: feedservice
          image: feedservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 8081
        - name: userservice
          image: userservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerport: 8081
      restartPolicy: Always