apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\denny\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: feedservice
  name: feedservice
spec:
  ports:
    - name: "5020"
      port: 5020
      targetPort: 8080
    - name: "5021"
      port: 5021
      targetPort: 8081
  selector:
    io.kompose.service: feedservice
