apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\denny\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ocelotgateway
  name: ocelotgateway
spec:
  ports:
    - name: "5554"
      port: 5554
      targetPort: 8080
    - name: "5555"
      port: 5555
      targetPort: 8081
  selector:
    io.kompose.service: ocelotgateway
