apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\denny\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postservice
  name: postservice
spec:
  ports:
    - name: "5010"
      port: 5010
      targetPort: 8080
    - name: "5011"
      port: 5011
      targetPort: 8081
  selector:
    io.kompose.service: postservice
