apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: postservice
  name: postservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postservice
  template:
    metadata:
      labels:
        io.kompose.service: postservice
    spec:
      containers:
        - name: postservice
          image: postservice:latest
          imagePullPolicy: Never 
          ports:
            - containerPort: 8080
            - containerPort: 8081
      restartPolicy: Always
